from django.urls import path

from . import views

app_name = "cms"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.dashboard_view, name="dashboard"),
    path("homepage/", views.homepage_manage_view, name="homepage_manage"),
    path("pages/", views.pages_manage_view, name="pages_manage"),
    path("media/upload-image/", views.editorjs_image_upload_view, name="editorjs_image_upload"),
    path("media/", views.media_manage_view, name="media_manage"),
    path("audit-logs/", views.audit_logs_view, name="audit_logs"),
    path("media/library-data/", views.media_library_data_view, name="media_library_data"),
    path("media/upload-file/", views.media_asset_upload_view, name="media_asset_upload"),
    path("media/<int:pk>/update/", views.media_update_view, name="media_update"),
    path("media/<int:pk>/delete/", views.media_delete_view, name="media_delete"),
    path("users/", views.users_manage_view, name="users_manage"),
    path("users/new/", views.user_create_view, name="user_create"),
    path("users/<int:pk>/edit/", views.user_edit_view, name="user_edit"),
    path("users/<int:pk>/delete/", views.user_delete_view, name="user_delete"),
    path("contact-submissions/", views.contact_submissions_manage_view, name="contact_submissions_manage"),
    path(
        "contact-submissions/<int:pk>/toggle/",
        views.contact_submission_toggle_view,
        name="contact_submission_toggle",
    ),
    path("services/", views.services_manage_view, name="services_manage"),
    path("services/new/", views.service_create_view, name="service_create"),
    path("services/<int:pk>/edit/", views.service_edit_view, name="service_edit"),
    path("services/<int:pk>/delete/", views.service_delete_view, name="service_delete"),
    path("testimonials/", views.testimonials_manage_view, name="testimonials_manage"),
    path("testimonials/new/", views.testimonial_create_view, name="testimonial_create"),
    path("testimonials/<int:pk>/edit/", views.testimonial_edit_view, name="testimonial_edit"),
    path("testimonials/<int:pk>/delete/", views.testimonial_delete_view, name="testimonial_delete"),
    path("faqs/", views.faqs_manage_view, name="faqs_manage"),
    path("faqs/new/", views.faq_create_view, name="faq_create"),
    path("faqs/<int:pk>/edit/", views.faq_edit_view, name="faq_edit"),
    path("faqs/<int:pk>/delete/", views.faq_delete_view, name="faq_delete"),
    path("projects/", views.projects_manage_view, name="projects_manage"),
    path("projects/new/", views.project_create_view, name="project_create"),
    path("projects/<int:pk>/edit/", views.project_edit_view, name="project_edit"),
    path("projects/<int:pk>/delete/", views.project_delete_view, name="project_delete"),
    path("careers/", views.careers_manage_view, name="careers_manage"),
    path("careers/new/", views.career_create_view, name="career_create"),
    path("careers/<int:pk>/edit/", views.career_edit_view, name="career_edit"),
    path("careers/<int:pk>/delete/", views.career_delete_view, name="career_delete"),
    path("blogs/", views.blogs_manage_view, name="blogs_manage"),
    path("blogs/new/", views.blog_create_view, name="blog_create"),
    path("blogs/<int:pk>/edit/", views.blog_edit_view, name="blog_edit"),
    path("blogs/<int:pk>/delete/", views.blog_delete_view, name="blog_delete"),
]
